# Generated by Django 5.0.6 on 2024-05-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_age_patient_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='weight',
        ),
    ]
