# Generated by Django 5.0.6 on 2024-06-06 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_sex_measures_measurements_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measures',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='measures',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='units',
            name='patient_id',
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_name', models.CharField(max_length=128)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_a', models.IntegerField(max_length=10)),
                ('value_b', models.IntegerField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('measure_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.measure')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=10)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.unit'),
        ),
        migrations.DeleteModel(
            name='Measurements',
        ),
        migrations.DeleteModel(
            name='Measures',
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
