# Generated by Django 5.0.6 on 2024-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_measures_patient_id_remove_measures_unit_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value_a',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value_b',
            field=models.IntegerField(),
        ),
    ]
