# Generated by Django 5.0.6 on 2024-06-06 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_measurement_value_a_alter_measurement_value_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 15, 26, 35, 56410)),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value_b',
            field=models.IntegerField(null=True),
        ),
    ]
