# Generated by Django 5.0.6 on 2024-06-15 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alter_measurement_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 11, 55, 42, 965072)),
        ),
    ]
