# Generated by Django 5.0.6 on 2024-06-15 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_alter_measurement_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 12, 45, 43, 876671)),
        ),
    ]
