<<<<<<< HEAD


# Generated by Django 5.0.6 on 2024-06-15 15:30


=======
>>>>>>> 726307325cf0486bc83418cff8fbf8016371a4be
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

<<<<<<< HEAD
        ('patients', '0021_alter_measurement_timestamp_alter_patient_image'),
=======
        ('patients', '0021_alter_measurement_timestamp'),
>>>>>>> 726307325cf0486bc83418cff8fbf8016371a4be

    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 30, 2, 265288)),
<<<<<<< HEAD

=======
>>>>>>> 726307325cf0486bc83418cff8fbf8016371a4be
        ),
    ]
