<<<<<<< HEAD

# Generated by Django 5.0.6 on 2024-06-15 15:30

=======
<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-15 15:30
=======
# Generated by Django 5.0.4 on 2024-06-15 15:38
>>>>>>> refs/remotes/origin/main
>>>>>>> a0c6ae94d8722e5259e613f4e9b8ba0517764fe9

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('patients', '0021_alter_measurement_timestamp'),
=======
        ('patients', '0021_alter_measurement_timestamp_alter_patient_image'),
<<<<<<< HEAD

=======
>>>>>>> refs/remotes/origin/main
>>>>>>> a0c6ae94d8722e5259e613f4e9b8ba0517764fe9
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 30, 2, 265288)),
=======
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 30, 2, 265288)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 38, 50, 948985)),
>>>>>>> refs/remotes/origin/main
>>>>>>> a0c6ae94d8722e5259e613f4e9b8ba0517764fe9
        ),
    ]
