<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-15 15:30
=======
# Generated by Django 5.0.4 on 2024-06-15 15:38
>>>>>>> 01727599706b100b78898ae21297c72414c22eb4

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('patients', '0021_alter_measurement_timestamp'),
=======
        ('patients', '0021_alter_measurement_timestamp_alter_patient_image'),
>>>>>>> 01727599706b100b78898ae21297c72414c22eb4
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='timestamp',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 30, 2, 265288)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 15, 17, 38, 50, 948985)),
>>>>>>> 01727599706b100b78898ae21297c72414c22eb4
        ),
    ]
